docs_branding: ODD Sénégal
docs_intro: Données ODD pour le Sénégal
docs_subfolder: data
schema_file: meta/_prose.yml

inputs:
  - class: InputCsvData
    path_pattern: data/*-*.csv

metadata_inputs:
  - class: InputYamlMdMeta
    path_pattern: meta/*
    git: false

translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: HEAD

automated_translation: false
