# Configuration de construction des donnees Open SDG.
# Documentation : https://open-sdg.readthedocs.io/en/latest/data-configuration/

site_dir: '_site'
schema_file: '_prose.yml'

inputs:
  - class: InputCsvData
    path_pattern: data/*-*.csv
  - class: InputYamlMeta
    path_pattern: meta/*-*.yml
    git: false

languages:
  - fr

translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: master

docs_branding: 'Suivi des ODD au Senegal'
docs_intro: 'Documentation du service de donnees ODD du Senegal.'
